arch: linear
aug: true
augmentation: RandomResizedCrop
batch_size: 240
ckpt: ''
ckpt_iter: -1
config_file: null
data: imagenet
dist: dp
dist_address: ''
encode_layer: h
encoder_ckpt: ''
eval_freq: 100
finetune: True
iters: 30000
log_freq: 100
lr: 0.1
lr_schedule: linear
model_id: -1
name: eval_imagenet_newmodels
node_rank: 0
opt: sgd
precompute_emb_bs: -1
problem: semi-supervised-eval
save_freq: 3000
scale_lower: 0.08
seed: -1
test_bs: 256
tmp: false
warmup: 0 #0.0025
weight_decay: 0 #0.001
workers: 20
world_size: 1
